provider_config:
  bms:
    ssh_user: root
    ssh_pwd: contrail123
    ntpserver: 210.173.160.27
    domainsuffix: localdomain

instances:
  bms1:
    provider: bms
    ip: 192.168.17.4
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      openstack:
  bms2:
    provider: bms
    ip: 192.168.17.5
    roles:
      vpp:
        VPP_CONTROL_ADDR: 192.168.17.10
        PHYSICAL_INTERFACE: enp2s0f1
        AGENT_MODE: dpdk
      openstack_compute:
  bms3:
    provider: bms
    ip: 192.168.17.6
    roles:
      vrouter:
        PHYSICAL_INTERFACE: enp2s0f1
        AGENT_MODE: dpdk
      openstack_compute:
contrail_configuration:
  CONTRAIL_VERSION: ocata-dev
  RABBITMQ_NODE_PORT: 5673
  ENCAP_PRIORITY: VXLAN,MPLSoGRE,MPLSoUDP
  PHYSICAL_INTERFACE: enp2s0f1
  AUTH_MODE: keystone
  KEYSTONE_AUTH_URL_VERSION: /v3
kolla_config:
  kolla_globals:
    network_interface: "enp2s0f1"
    kolla_external_vip_interface: "enp2s0f1"
    enable_swift: no
    enable_haproxy: no
  kolla_passwords:
    keystone_admin_password: contrail123
global_configuration:
  CONTAINER_REGISTRY: 192.168.19.4:6666
  REGISTRY_PRIVATE_INSECURE: True
